config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  post 'pay2go/return'
  post 'pay2go/notify'

  resources :users, only:[:show], :controller => 'user_profiles'

  resources :donations, only:[:index], :controller => 'donations'

  resources :plans do 
  	resources :comments, only:[:create,:destroy], :controller => 'plan_comments'
    resources :donations, only:[:new, :create, :show], :controller => 'plan_donations' do 
      member do
        post :checkout_pay2go
      end
    end
    resources :photos, only:[:create, :destroy], :controller => 'plan_photos'
  	collection do
      get :latest
      get :follow_plan
      get :like_plan
    end
    member do 
    	post :follow
    	post :unfollow
      post :like
      post :unlike
    end
  end

  resources :tag_categories, only:[:show], :controller => 'tag_categories'


  namespace :listadmin do
    resources :users
    resources :tag_categories
  end


  get"/home", to:"home#homepage", :controller => 'home'
  get"/about", to:"home#about", :controller => 'home'
  get"/how_it_works", to:"home#works", :controller => 'home'

  root "home#homepage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/comment.rb
class Comment < ApplicationRecord
	has_attached_file :image,:default_url => 'upload_image.png', styles: { small: "100x100"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates_presence_of :comment_body
 	belongs_to :plan,	:counter_cache => true
 	default_scope { order(created_at: :desc) }
end

app/models/donation.rb
class Donation < ApplicationRecord
	validates_presence_of :cc_name, :amount
	belongs_to :npo
	belongs_to :plan
	belongs_to :user
	has_many :payments
	
	def paid?
		self.payment_status == "Paid"
	end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :plan
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :user
	belongs_to :plan
end

app/models/npo.rb
class Npo < ApplicationRecord
	has_many :donations
end

app/models/payment.rb
class Payment < ApplicationRecord
	PAYMENT_METHODS = %w[Credit WebATM] # ATM CVS BARCODE
	validates_inclusion_of :payment_method, :in => PAYMENT_METHODS
	belongs_to :donation
	serialize :params, JSON
	validate :check_mac, on: :update
	after_update :update_donation_status

	def name
	  "Bucketlist donation"
	end

	def email
	  self.donation.user.email
	end

	def external_id
		"#{self.id}AC12#{Rails.env.upcase[0]}"
	end

	def self.find_and_process(params)
		result = JSON.parse( params['Result'] )
		payment = self.find(result['MerchantOrderNo'].to_i)
		if params['Status'] == 'SUCCESS'
			payment.paid_at = Time.now
		end
		payment.params = params
		payment
	end

	def parse_result
		JSON.parse( self.params['Result'] )
	end

	def check_mac
		pay2go = Pay2go.new(parse_result)
		errors.add(:params, 'wrong mac value') unless pay2go.check_mac
	end

	def update_donation_status
		if self.paid_at
			self.donation.update( :payment_status => "Paid" )
		end
	end

end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :plan
	has_attached_file :image, styles: { med: "100x100"},:default_url => 'upload_more_image.png'
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/plan.rb
class Plan < ApplicationRecord
	has_attached_file :file_location, styles: { med: "100x100"},:default_url => 'default.png'
	validates_attachment_content_type :file_location, content_type: /\Aimage\/.*\z/
	validates_presence_of :title, :message => "願望主題不能空白"
	validates :title, length: { maximum: 20 ,too_long: "不能超過20字"}
	validates_presence_of :duedate, :message => "預計完成日不能空白"


	has_many :memberships , dependent: :destroy
	has_many :users, :through => :memberships 

	has_many :likes , dependent: :destroy
	has_many :users, :through => :likes

	has_many :comments, dependent: :destroy

	has_many :tag_plan_rp
	has_many :tag_categories, :through => :tag_plan_rp

	has_one :donation
	
	has_many :photos , dependent: :destroy


	
	def find_follow(user)
		Membership.find_by(:plan => self, :user => user)
	end

	def already_followed(user)
		find_follow(user).present?
	end

	def find_like(user)
		Like.find_by(:plan => self, :user => user)
	end

	def already_liked(user)
		find_like(user).present?
	end

end

app/models/tag_category.rb
class TagCategory < ApplicationRecord
	has_many :tag_plan_rp
	has_many :plans, :through => :tag_plan_rp
end

app/models/tag_plan_rp.rb
class TagPlanRp < ApplicationRecord
	belongs_to :tag_category
	belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :nickname, use: :slugged
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :memberships
  has_many :plans, :through => :memberships

  has_many :likes
  has_many :plans, :through => :likes
  has_many :donations
  before_validation :set_nickname_default
  


  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
    end

    private

    def set_nickname_default
      self.nickname = self.email.split("@").first
    end

    


end

app/controllers/plan_comments_controller.rb
class PlanCommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_plan


	def create
		@comment=@plan.comments.new(comment_params)
		if @comment.save
			respond_to do |format|
	      format.html { redirect_to plan_path(@plan)}
	      format.js	 # create.js.erb
    	end
		else
			flash[:alert] = "請至少輸入ㄧ個字!"	
		end

	end


	def destroy
		
		@comment=@plan.comments.find(params[:id])
		@comment.destroy
		if @comment.commenter == current_user.nickname || @plan.host == current_user.nickname ||current_user.role == "admin"
			respond_to do |format|
	      format.html { redirect_to plan_path(@plan)}
	      format.js	 # destroy.js.erb
    	end
			
		else
			flash[:alert] = "something went wrong!"	
		end

	end

	private

	def find_plan
		@plan=Plan.find(params[:plan_id])
	end

	def comment_params
		params.require(:comment).permit(:comment_body, :commenter, :image )
	end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pay2go_helper.rb
module Pay2goHelper
	def generate_pay2go_params(payment)
	pay2go_params = {
		MerchantID: Pay2go.merchant_id,
		RespondType: "JSON",
		TimeStamp: payment.created_at.to_i,
		Version: "1.2",
		LangType: I18n.locale.downcase, # zh-tw or en
		MerchantOrderNo: payment.external_id,
		Amt: payment.amount,
		ItemDesc: payment.name,
		ReturnURL: pay2go_return_url,
		NotifyURL: Pay2go.notify_url,
		Email: payment.email,
		LoginType: 0,
		CREDIT: 0,
		WEBATM: 0,
		VACC: 0,
		CVS: 0,
		BARCODE: 0
	 }

	case payment.payment_method
		when "Credit"
			pay2go_params.merge!( :CREDIT => 1 )
		when "WebATM"
			pay2go_params.merge!( :WEBATM => 1 )
		when "ATM"
			pay2go_params.merge!( :VACC => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
		when "CVS"
			pay2go_params.merge!( :CVS => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
		when "BARCODE"
			pay2go_params.merge!( :BARCODE => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
		end

		pay2go = Pay2go.new(pay2go_params)
		pay2go_params[:CheckValue] = pay2go.make_check_value
		pay2go_params
	end


	
end

app/helpers/plan_comments_helper.rb
module PlanCommentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/plan_comments/_comment.html.erb
	  <div id="comment-<%= c.id %>">
		  <br>
		 <i class="fa fa-user-o" aria-hidden="true">&nbsp;<%= c.commenter %></i>&nbsp;&nbsp;<%= time_ago_in_words(c.created_at)%><strong>前</strong>
		 	<p><%= c.comment_body %> </p>
		 	<div id="image">
				<% if c.image_file_name %>
			 		<%= link_to image_tag(c.image.url(:small)), c.image.url %>
				<% end %>
			</div>
				<% if c.commenter == current_user.nickname || @plan.host == current_user.nickname ||current_user.role == "admin" %>
					<%= link_to 'Destroy Comment', plan_comment_path(@plan,c) ,method: :delete,method: :delete, data:{ confirm: "確定要刪除留言嗎?"},:remote => true %>
				<% end %>
		</div>
	
		

app/views/plan_comments/_form.html.erb
<div class="container preview">
<%= form_for [@plan, @plan.comments.new] , html: { multipart: true } ,:remote => true  do |f| %> 

    <i class="fa fa-user-circle-o fa-2x" aria-hidden="true"></i>

        <%= f.text_field :commenter,:value => current_user.nickname,:readonly => true%>
    <div>
        <%= f.label :comment_body,"留言嗎？" %><br>
        <%= f.text_area :comment_body ,:required => 'required',:id => "comment-text"%><br>
        <%= f.file_field :image ,:id => "image-text" ,class:"file" %>
        <div class="upload-preview">
         	<% if @plan.comments.new.image.url %>		
       			<%= image_tag @plan.comments.new.image.url ,class:"resize-small" %>
       		<% end %>
				</div>

       	
        <%= f.submit "留言",class:"btn", id:"btn"%> 
    </div>

        

<% end %>
		
				

</div>

<script type="text/javascript">
 $("document").ready(function(){
	
	

	var preview = $(".upload-preview img");

    $(".file").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
    

	});
</script>

app/views/plan_comments/create.js.erb
<% if @comment.save  %>

	$("#comment-list").prepend("<%=j render(:partial => 'plan_comments/comment', :locals => {:c => @comment })%>");
	$("#count").text('<%= @plan.comments.count %>');

	$("#comment-text").val("");
	$("#image-text").val("");

  $(".upload-preview img").attr("src","/assets/upload_image.png");
<% end %>

app/views/plan_comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

$("#count").text('<%= @plan.comments.count %>');