config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  post 'pay2go/return'
  post 'pay2go/notify'

  resources :users, only:[:show], :controller => 'user_profiles'

  resources :donations, only:[:index], :controller => 'donations'

  resources :plans do 
  	resources :comments, only:[:create,:destroy], :controller => 'plan_comments'
    resources :donations, only:[:new, :create, :show], :controller => 'plan_donations' do 
      member do
        post :checkout_pay2go
      end
    end
    resources :photos, only:[:create, :destroy], :controller => 'plan_photos'
  	collection do
      get :latest
      get :follow_plan
      get :like_plan
    end
    member do 
    	post :follow
    	post :unfollow
      post :like
      post :unlike
    end
  end

  resources :tag_categories, only:[:show], :controller => 'tag_categories'


  namespace :listadmin do
    resources :users
    resources :tag_categories
  end


  get"/home", to:"home#homepage", :controller => 'home'
  get"/about", to:"home#about", :controller => 'home'
  get"/how_it_works", to:"home#works", :controller => 'home'

  root "home#homepage"
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_attached_file :file_location, styles: { med: "100x100"},:default_url => 'default.png'
	validates_attachment_content_type :file_location, content_type: /\Aimage\/.*\z/
	validates_presence_of :title, :message => "願望主題不能空白"
	validates :title, length: { maximum: 20 ,too_long: "不能超過20字"}
	validates_presence_of :duedate, :message => "預計完成日不能空白"


	has_many :memberships , dependent: :destroy
	has_many :users, :through => :memberships 

	has_many :likes , dependent: :destroy
	has_many :users, :through => :likes

	has_many :comments, dependent: :destroy

	has_many :tag_plan_rp
	has_many :tag_categories, :through => :tag_plan_rp

	has_one :donation
	
	has_many :photos , dependent: :destroy


	
	def find_follow(user)
		Membership.find_by(:plan => self, :user => user)
	end

	def already_followed(user)
		find_follow(user).present?
	end

	def find_like(user)
		Like.find_by(:plan => self, :user => user)
	end

	def already_liked(user)
		find_like(user).present?
	end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
	before_action :authenticate_user!, except:[:latest,:show]
	before_action :find_plan, only:[:show, :edit, :update, :destroy, :follow, :unfollow, :like, :unlike, :morecomments]

	def index
			@page_title = "你的願望清單"
			@current_user_plan = Plan.where(:host => current_user.nickname)
			#if params[:keyword]
	    #	@plans = @current_user_plan.where( [ "title like ?", "%#{params[:keyword]}%" ] )
	  	#else
	  	
	  	@plans = @current_user_plan.page(params[:page]).per(21)
	  	@num = @plans.count
	  	@success = @plans.where(:progress => "完成計畫").count
	  	respond_to do |format|
		    format.html # index.html.erb
		    #format.json { render :json => @plans.to_json }
 			 end

	  	if params[:order]
	  		sort_by = (params[:order] == 'duedate') ? 'duedate' : 'duedate'
	  		@plans = @current_user_plan.order(sort_by).page(params[:page]).per(9)
	   
	  	end

	  	
	end

	def new
		@page_title = "新增願望"
		@plan = Plan.new

	end

	def create
		@plan = Plan.new(permit_plan)
		@plan.host = current_user.nickname

		
		if @plan.save
			
			respond_to do |format|
				  format.html { redirect_to plans_path}
				  format.js
			end		
		else 
			render :new
		end
		
	end

	def show
		
		@comment_no = @plan.comments_count
		@follow_count = @plan.memberships.count
		@like_count = @plan.likes.count
		@plan.page_view ||= 0
		@plan.page_view +=1
		@plan.save

		@comments = @plan.comments.page(params[:page]).per(5)
		
		if @comments.last_page?
      @next_page = nil
    else
      @next_page = @comments.next_page
    end

		respond_to do |format|
			format.html {@page_title = @plan.title }
			format.js
		end		



	end


	
	def edit 
		@page_title = "編輯願望"
		unless @plan.host == current_user.nickname || current_user.role == "admin"
			render :latest
			flash[:alert] = "something went wrong!"
		end

	end

	def update

		if @plan.host == current_user.nickname || current_user.role == "admin"
			if @plan.update(permit_plan)
				redirect_to plan_path(@plan)
			else
				render :edit
			end
		else 
			render :latest
			flash[:alert] = "something went wrong!"	
		end
	end

	def destroy
		if @plan.host == current_user.nickname || current_user.role == "admin"

			@plan.destroy

			redirect_to plans_path

			
		else
			flash[:alert] = "something went wrong!"	
		end

	end

	def follow
		
		unless @plan.host == current_user.nickname || @plan.already_followed(current_user)
			@membership = Membership.create(:user => current_user, :plan => @plan)
			redirect_to plan_url(@plan)
		end
	end

	def unfollow

		if @plan.already_followed(current_user)
			@membership = @plan.find_follow(current_user)
			@membership.destroy
			redirect_to plan_url(@plan)
		end

	end

	def like 
		unless @plan.host == current_user.nickname || @plan.already_liked(current_user)
			@like = Like.create(:user => current_user, :plan => @plan)
			redirect_to plan_url(@plan)
		end

	end

	def unlike
		if @plan.already_liked(current_user)
			@like = @plan.find_like(current_user)
			@like.destroy
			redirect_to plan_url(@plan)
		end

	end


	def follow_plan
		@page_title = "你Follow的plan"
		@plans = current_user.memberships.page(params[:page]).per(9)
	   
	end


	def like_plan
		@page_title = "你like的plan"
		@plans = current_user.likes.page(params[:page]).per(9)
	end

	def latest
		@page_title = "大家的願望清單"
		

		if params[:order]== 'comments_count'
			@plans = Plan.where(:is_public => true).order('comments_count desc').page(params[:page]).per(30)
	   
		
		elsif params[:comment_last] == 'comment_last'

			@plans = Plan.where(:is_public => true).includes(:comments).order('comments.created_at desc').page(params[:page]).per(30)
	   
		
		elsif params[:view]== 'view'
			
			@plans = Plan.where(:is_public => true).order('page_view desc').page(params[:page]).per(30)
		else
			
			@plans = Plan.where(:is_public => true).order('created_at desc').page(params[:page]).per(30)
	   

		end
		
		
	end

	
	
	private

	def permit_plan
		params.require(:plan).permit(:title, :duedate, :plan, :do_what, :check, :act, :file_location, :is_public, :progress,:why, :tag_category_ids => [])
	end

	def find_plan
		@plan = Plan.find(params[:id])
	end

end

app/helpers/admin/plans_helper.rb
module Admin::PlansHelper
end

app/helpers/listadmin/plans_helper.rb
module Listadmin::PlansHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_list.html.erb
<% @comments.each do |c| %>
  <%= render :partial => "plan_comments/comment", :locals => { :c => c} %>
<% end %>

app/views/plans/_only.html.erb
<% if Time.now < @plan.duedate %>
	<% if @plan.donation %>
		<%= link_to '查看押金', plan_donation_path(@plan),class:"btn"%>
	<% else %>
		<%= link_to '設定決心押金', new_plan_donation_path(@plan) ,class:"btn"%>
	<% end %>
<% end %>

<%= link_to '修改', edit_plan_path(@plan),class:"btn" %>
<%= link_to '刪除', plan_path(@plan),method: :delete, data:{ confirm: "確定要刪除願望嗎?"},class:"btn" %>

app/views/plans/edit.html.erb
<% if @plan.host == current_user.nickname || current_user.role == "admin" %>


		
		<%= render :partial => "form" %>


<% end %>

app/views/plans/follow_plan.html.erb
<div  class="container">
	<h1 class="tc">你follow的plans </h1>
</div>
<div class="toolbox">
	<div class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-search-plus  fa-2x" aria-hidden="true">清單放大鏡</i><span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><%= link_to '新增願望?', new_plan_path%></li>
			<li><%= link_to '回上ㄧ頁', plans_path %></li>		
		</ul>
	</div>
</div>

<div class="container">
	<div class="row">
  
		<% @plans.each do |p| %>
			<div class="col-md-4">
				<table class="table table-bordered">
					<tr>
					  <th><%= p.plan.title %></th>
						
					</tr>
					
					<tr>
						<td>預計完成日: <%= p.plan.duedate%></td>
						
					</tr>
					<tr>
						<td colspan="2"><%= image_tag p.plan.file_location ,class:"resize-latest" %></td>
					</tr>
					<tr>
						<td colspan="2"><p>主辦人:<%=p.plan.host%></p></td>
					</tr>
					<tr>
						<td colspan="2"><%= link_to 'Detail', plan_path(p.plan.id) %> </td>
					</tr>
				</table>	
			</div>
		<% end %>
	 
	</div>
</div>

<div class="container text-center">
	<%=paginate @plans%>
</div>

app/views/plans/index.html.erb
<div class="container text-center">
	<h1 class="tc">你的願望清單</h1>
	<h4>您擁有<%= @num %>個人生願望，目前已完成<%= @success %>個了喔，加油！！！</h4>	
	
</div>
 

<div class="toolbox">
		<div class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-search-plus fa-2x" aria-hidden="true">放大鏡</i><span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><%= link_to '新增願望?', new_plan_path%></li>				
					<%#= form_tag plans_path, :method => :get do %>
					<%#= text_field_tag "keyword" %>
					<%#= submit_tag "Search" ,class:"btn" %>	
				<li><%= link_to '依預計完成日排序', plans_path( :order => "duedate") %></li>
				<li><%= link_to '預設排序', plans_path %></li>
				<li><%= link_to '查看你Follow的plans', follow_plan_plans_path %></li>
				<li><%= link_to '查看你like的plans', like_plan_plans_path %></li>
				<li><%= link_to '查看個人公開profile', user_path(@current_user.id) %></li>
				<li><%= link_to '查看個人的押金記錄', donations_path %></li>

				<% unless current_user.role == "user" %>
     			<li><%= link_to '前往後台', listadmin_users_path ,class:"btn btn default"%></li>
 				<% end %>
			</ul>
		</div>
</div>


<div class="container">
	<div class="row">
		<% @plans.each do |p| %>
			<div class = "col-md-4" >
				<table class="table table-bordered">
				<tr>
				  <th class="table-info"><%= p.title%></th>
				</tr>
				
				<tr>
					<td><p>預計完成日: <%= p.duedate%></p><p>進度：<%= p.progress %></p></td>
				</tr>
				<tr>
					<td colspan="2"><%= image_tag p.file_location ,class:"resize-latest"%></td>
				</tr>
				<tr>
					<td colspan="2">是否公開: <%= p.is_public %>		
						<% p.tag_categories.each do |t| %>
		   			<i class="fa fa-tag" aria-hidden="true"><%= t.name %></i>
						<% end %>
					</td>
				</tr>
			
				<tr>
					<td colspan="2"><%= link_to 'Detail', plan_path(p) %> </td>
				</tr>
				</table>
			</div>			 	
		<% end %>
	</div>
</div>
<div class="container text-center">
	<%=paginate @plans%>
</div>

app/views/plans/latest.html.erb
<div class="container">
	<h1>大家的願望清單</h1>
	
</div>

<div class="container">
	
	
	
	<p><i>依願望分類搜尋:</i>&nbsp;&nbsp;&nbsp;

	<% TagCategory.all.each do |t| %>

		<i class="fa fa-tag " aria-hidden="true"><%= link_to t.name, tag_category_path(t.id)%>&nbsp;&nbsp;</i>
						
	<% end %>

	</i></p>
		<p><i>排序:</i>&nbsp;&nbsp;&nbsp;
		<i class="fa fa-sort" aria-hidden="true"><%= link_to '最多留言', latest_plans_path( :order => "comments_count") %></i>&nbsp;&nbsp;
		<i class="fa fa-sort" aria-hidden="true"><%= link_to '最後回覆', latest_plans_path( :comment_last =>"comment_last") %></i>&nbsp;&nbsp;
		
		<i class="fa fa-sort" aria-hidden="true"><%= link_to '最多瀏覽', latest_plans_path( :view =>	"view") %></i>&nbsp;&nbsp;
		<i class="fa fa-sort" aria-hidden="true"><%= link_to '最近上傳', latest_plans_path %></i>
		</p>

	
</div>

<div class="container">
	<div class="row">
  
		<% @plans.each do |p| %>
			<div class="col-md-4">
				<table class="table table-bordered">
					<tr>
					  <th><%=truncate(p.title, length: 20) %></th>
						
					</tr>
					
					<tr>
						<td><i class="fa fa-eye" aria-hidden="true">&nbsp;<%= p.page_view %></i>&nbsp;&nbsp;&nbsp;<i class="fa fa-bookmark" aria-hidden="true">	&nbsp;<%= p.memberships.count %></i>&nbsp;&nbsp;<i class="fa fa-heart" aria-hidden="true">&nbsp;<%= p.likes.count %></i>&nbsp;&nbsp;<i class="fa fa-commenting" aria-hidden="true">&nbsp;<%= p.comments_count%></i>
				
						</td>
						
					</tr>
					<tr>
						<td>最近更新: <%= time_ago_in_words(p.updated_at) %> 之前</td>
						
					</tr>

					<tr>
						<td><%= image_tag p.file_location ,class:"resize-latest" %></td>
					</tr>
					<tr>
						
						<% @user= User.find_by(:nickname => p.host) %>
						<td><%= link_to p.host, user_path(@user.to_param) %>
						<% p.tag_categories.each do |t| %>
		   			<i class="fa fa-tag" aria-hidden="true"><%= t.name %></i>
						<% end %>
						</td>
					</tr>
					
					<tr>
						<td><%= link_to 'Detail', plan_path(p) %> </td>
					</tr>
				</table>	
			</div>
		<% end %>
	 
	</div>
</div>
<div class="container text-center">
	<%= paginate @plans %>
</div>

app/views/plans/like_plan.html.erb
<div  class="container">
	<h1 class="tc">你like的plans </h1>
</div>
<div class="toolbox">
	<div class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-search-plus  fa-2x" aria-hidden="true">清單放大鏡</i><span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><%= link_to '新增願望?', new_plan_path%></li>
			<li><%= link_to '回上ㄧ頁', plans_path %></li>		
		</ul>
	</div>
</div>

<div class="container">
	<div class="row">
  
		<% @plans.each do |p| %>
			<div class="col-md-4">
				<table class="table table-bordered">
					<tr>
					  <th><%= p.plan.title %></th>
						
					</tr>
					
					<tr>
						<td>預計完成日: <%= p.plan.duedate%></td>
						
					</tr>
					<tr>
						<td colspan="2"><%= image_tag p.plan.file_location ,class:"resize-latest" %></td>
					</tr>
					<tr>
						<td colspan="2"><p>主辦人:<%=p.plan.host%></p></td>
					</tr>
					<tr>
						<td colspan="2"><%= link_to 'Detail', plan_path(p.plan.id) %> </td>
					</tr>
				</table>	
			</div>
		<% end %>
	 
	</div>
</div>
<div class="container text-center">
	<%=paginate @plans%>
</div>

app/views/plans/show.html.erb
<div class="container text-center">

<h2>
<%= @plan.title %> <br>
</h2>
<h4> 預計完成日: <%= @plan.duedate %> 作者: <%=@plan.host%> </h4>

	<% @plan.tag_categories.each do |t| %>
		<i class="fa fa-tag" aria-hidden="true"><%= t.name %></i>
	<% end %>

	<% if Time.now > @plan.duedate %>
		<h4>已到期！</h4>

	<% end %>

</div>


<div class= "follow_like">
	<% if current_user %>
		<% unless @plan.host == current_user.nickname || current_user.role == "admin" %>
			<div class="col-md-2 see-follow">
				<% if @plan.already_followed(current_user) %>	
					<%= button_to unfollow_plan_path(@plan) , {:remote => true} do %>
						<i class="fa fa-bookmark fa-2x" aria-hidden="true"><%= @follow_count %></i>
					<% end %>
				<%else%>			
					<%= button_to follow_plan_path(@plan) ,{:remote => true} do %>
						<i class="fa fa-bookmark-o fa-2x" aria-hidden="true"><%= @follow_count %></i>
					<% end %>
				<% end %>
				<div class="who-follow">
					<% if @follow_count < 1 %>
					  <p>目前還沒有人收藏</p>
					<% else %>
						<p>See who follow</p>
							<% @plan.memberships.each do |f| %>
								<%= f.user.nickname %>&nbsp;
							<% end %>
					<% end %>
				</div>
			</div>
			<div class="col-md-2 see-like">
				<% if @plan.already_liked(current_user) %>			
					<%= button_to unlike_plan_path(@plan) , {:remote => true} do %>
						<i class="fa fa-heart fa-2x" aria-hidden="true"><%= @like_count %></i>
					<% end %>
				<%else%>			
					<%= button_to like_plan_path(@plan) ,{:remote => true} do %>
						<i class="fa fa-heart-o fa-2x" aria-hidden="true"><%= @like_count %></i>
					<% end %>
				<% end %>
				<div class="who-like">
					<% if @like_count < 1 %>
					  <p>目前還沒有人like</p>
					<% else %>
						<p>See who like</p>
							<% @plan.likes.each do |f| %>
								<%= f.user.nickname %>&nbsp;
							<% end %>
						</ol>
					<% end %>
				</div>
			</div>
		<% end %>	
	<% end %>
	<div class="col-md-2">
		<%= render_shareable :buttons => ['google_plus'] %>
	</div>
	<div class="col-md-2">
		<i class="fa fa-eye" aria-hidden="true">&nbsp;<%= @plan.page_view %></i>&nbsp;&nbsp;&nbsp;
	</div>
</div>


<div class="navi">
<% if current_user %>
	<%if current_user && current_user.nickname == @plan.host || current_user.role == "admin" %>
		<%= render :partial => "only" %>
		
	<% end %>
<% end %>	
</div>

<div class="container text-center">

			<%= image_tag @plan.file_location.url ,class:"resize"%>	<br><br>
			<% if current_user %>
				<%if current_user && current_user.nickname == @plan.host || current_user.role == "admin" %>
					<h4><i class="fa fa-lock" aria-hidden="true">是否公開：</i>
					<%=  @plan.is_public %><br></h4>
				<% end %>
			<% end %>

			<h4><i class="fa fa-tasks" aria-hidden="true">目前進度：</i><%= @plan.progress %>
</div>


<div class="container" id="photo-list">
	<div class="row">
		<% @plan.photos.each do |p| %>
			<%= render :partial => 'plan_photos/photo', :locals => {:p => p }%>					
		<% end %>
	</div>
<div class="container">
	<% if current_user %>
		<% if current_user.role == "admin" ||	@plan.host == current_user.nickname %>
			<div class="row">
				<div class="col-md-2">
					<%= render :partial => 'plan_photos/newphoto' %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			<i class="fa fa-lightbulb-o fa-3x" aria-hidden="true"></i><i class="fa fa-question fa-3x" aria-hidden="true"></i><p><strong>動機</strong></p>
		</div>
		<div class="col-md-10 show">
			
			<%= sanitize( @plan.why ) %>
			
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			<i class="fa fa-calendar-plus-o fa-3x" aria-hidden="true"></i><p><strong>Plan計畫</strong></p>
		</div>
		<div class="col-md-10 show">
			<%= sanitize( @plan.plan) %>
			<%#= @plan.plan %> 
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			<i class="fa fa-calendar-plus-o fa-3x" aria-hidden="true"></i><p><strong>Do執行</strong></p>
		</div>
		<div class="col-md-10 show">
			<%= sanitize( @plan.do_what ) %>		
			<%#= @plan.do_what %> 
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			<i class="fa fa-calendar-plus-o fa-3x" aria-hidden="true"></i><p><strong>Check檢視</strong></p>
		</div>

		<div class="col-md-10 show">	
			<%= sanitize( @plan.check ) %>		
			<%#= @plan.check %> 
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			<i class="fa fa-calendar-plus-o fa-3x" aria-hidden="true"></i><p><strong>Action行動</strong></p>
		</div>


		<div class="col-md-10 show">		
			<%= sanitize( @plan.act ) %>	
			<%#= @plan.act %>
		</div>
	</div>

</div>


<div class="container">
	
</div>
<div class="container">		

	<% if current_user %>
	<hr>
		<div class="container">
		  <h3>目前:<span id="count"><%= @comment_no %></span> 則留言<i class="fa fa-commenting" aria-hidden="true"></i></h3>

		  
			<%= render :partial => 'plan_comments/form' %>
		</div>
			<div class="container" id="comment-list">
				<% @comments.each do |c| %>
					<%= render :partial => 'plan_comments/comment', :locals => {:c => c }%>
					
				<% end %>

			</div>

			<% paginate @comments %>

			
			<% if @next_page %>
				<%= link_to '更多留言',plan_path(@plan, :page => @next_page) ,:id => 'load-more',:remote => true %>
			<% end %>
<% else %>

  <h3>登入就可觀看留言</h3>
 <% end %>

</div>


	




<script type="text/javascript">
$("document").ready(function(){
	$(window).scroll(function(){
    if ( $(window).scrollTop() > $(document).height() - $(window).height()  ) {
      var url = $("#load-more").attr("href");
      if (url) {
        $.ajax({
          type: "GET",
          url: url,
          dataType: "script"
        })
      } else {
        console.log("data ended")
      }
    }
  })
 
});
</script>

app/views/plans/show.js.erb
var html = "<%= j( render :partial => "list" ) %>";
$("#comment-list").append(html);


<% if @next_page %>
 $("#load-more").attr("href", "<%= plan_path(@plan,:page => @next_page) %>")
<% else %>
 $("#load-more").remove();
<% end %>