config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  post 'pay2go/return'
  post 'pay2go/notify'

  resources :users, only:[:show], :controller => 'user_profiles'

  resources :donations, only:[:index], :controller => 'donations'

  resources :plans do 
  	resources :comments, only:[:create,:destroy], :controller => 'plan_comments'
    resources :donations, only:[:new, :create, :show], :controller => 'plan_donations' do 
      member do
        post :checkout_pay2go
      end
    end
    resources :photos, only:[:create, :destroy], :controller => 'plan_photos'
  	collection do
      get :latest
      get :follow_plan
      get :like_plan
    end
    member do 
    	post :follow
    	post :unfollow
      post :like
      post :unlike
    end
  end

  resources :tag_categories, only:[:show], :controller => 'tag_categories'


  namespace :listadmin do
    resources :users
    resources :tag_categories
  end


  get"/home", to:"home#homepage", :controller => 'home'
  get"/about", to:"home#about", :controller => 'home'
  get"/how_it_works", to:"home#works", :controller => 'home'

  root "home#homepage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/comment.rb
class Comment < ApplicationRecord
	has_attached_file :image,:default_url => 'upload_image.png', styles: { small: "100x100"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates_presence_of :comment_body
 	belongs_to :plan,	:counter_cache => true
 	default_scope { order(created_at: :desc) }
end

app/models/donation.rb
class Donation < ApplicationRecord
	validates_presence_of :cc_name, :amount
	belongs_to :npo
	belongs_to :plan
	belongs_to :user
	has_many :payments
	
	def paid?
		self.payment_status == "Paid"
	end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :plan
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :user
	belongs_to :plan
end

app/models/npo.rb
class Npo < ApplicationRecord
	has_many :donations
end

app/models/payment.rb
class Payment < ApplicationRecord
	PAYMENT_METHODS = %w[Credit WebATM] # ATM CVS BARCODE
	validates_inclusion_of :payment_method, :in => PAYMENT_METHODS
	belongs_to :donation
	serialize :params, JSON
	validate :check_mac, on: :update
	after_update :update_donation_status

	def name
	  "Bucketlist donation"
	end

	def email
	  self.donation.user.email
	end

	def external_id
		"#{self.id}AC12#{Rails.env.upcase[0]}"
	end

	def self.find_and_process(params)
		result = JSON.parse( params['Result'] )
		payment = self.find(result['MerchantOrderNo'].to_i)
		if params['Status'] == 'SUCCESS'
			payment.paid_at = Time.now
		end
		payment.params = params
		payment
	end

	def parse_result
		JSON.parse( self.params['Result'] )
	end

	def check_mac
		pay2go = Pay2go.new(parse_result)
		errors.add(:params, 'wrong mac value') unless pay2go.check_mac
	end

	def update_donation_status
		if self.paid_at
			self.donation.update( :payment_status => "Paid" )
		end
	end

end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :plan
	has_attached_file :image, styles: { med: "100x100"},:default_url => 'upload_more_image.png'
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/plan.rb
class Plan < ApplicationRecord
	has_attached_file :file_location, styles: { med: "100x100"},:default_url => 'default.png'
	validates_attachment_content_type :file_location, content_type: /\Aimage\/.*\z/
	validates_presence_of :title, :message => "願望主題不能空白"
	validates :title, length: { maximum: 20 ,too_long: "不能超過20字"}
	validates_presence_of :duedate, :message => "預計完成日不能空白"


	has_many :memberships , dependent: :destroy
	has_many :users, :through => :memberships 

	has_many :likes , dependent: :destroy
	has_many :users, :through => :likes

	has_many :comments, dependent: :destroy

	has_many :tag_plan_rp
	has_many :tag_categories, :through => :tag_plan_rp

	has_one :donation
	
	has_many :photos , dependent: :destroy


	
	def find_follow(user)
		Membership.find_by(:plan => self, :user => user)
	end

	def already_followed(user)
		find_follow(user).present?
	end

	def find_like(user)
		Like.find_by(:plan => self, :user => user)
	end

	def already_liked(user)
		find_like(user).present?
	end

end

app/models/tag_category.rb
class TagCategory < ApplicationRecord
	has_many :tag_plan_rp
	has_many :plans, :through => :tag_plan_rp
end

app/models/tag_plan_rp.rb
class TagPlanRp < ApplicationRecord
	belongs_to :tag_category
	belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :nickname, use: :slugged
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :memberships
  has_many :plans, :through => :memberships

  has_many :likes
  has_many :plans, :through => :likes
  has_many :donations
  before_validation :set_nickname_default
  


  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
    end

    private

    def set_nickname_default
      self.nickname = self.email.split("@").first
    end

    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pay2go_helper.rb
module Pay2goHelper
	def generate_pay2go_params(payment)
	pay2go_params = {
		MerchantID: Pay2go.merchant_id,
		RespondType: "JSON",
		TimeStamp: payment.created_at.to_i,
		Version: "1.2",
		LangType: I18n.locale.downcase, # zh-tw or en
		MerchantOrderNo: payment.external_id,
		Amt: payment.amount,
		ItemDesc: payment.name,
		ReturnURL: pay2go_return_url,
		NotifyURL: Pay2go.notify_url,
		Email: payment.email,
		LoginType: 0,
		CREDIT: 0,
		WEBATM: 0,
		VACC: 0,
		CVS: 0,
		BARCODE: 0
	 }

	case payment.payment_method
		when "Credit"
			pay2go_params.merge!( :CREDIT => 1 )
		when "WebATM"
			pay2go_params.merge!( :WEBATM => 1 )
		when "ATM"
			pay2go_params.merge!( :VACC => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
		when "CVS"
			pay2go_params.merge!( :CVS => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
		when "BARCODE"
			pay2go_params.merge!( :BARCODE => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
		end

		pay2go = Pay2go.new(pay2go_params)
		pay2go_params[:CheckValue] = pay2go.make_check_value
		pay2go_params
	end


	
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/df1bf87ec0.js"></script>
   <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">



  </head>

  <body>
  	<%= yield %>
  </body>
</html>

<script>
 var editor = new MediumEditor('.editable', {
    toolbar: {
        allowMultiParagraphSelection: true,
        buttons: ['bold', 'italic', 'h4','orderedlist','unorderedlist'],
        diffLeft: 0,
        diffTop: -10,
        firstButtonClass: 'medium-editor-button-first',
        lastButtonClass: 'medium-editor-button-last',
        relativeContainer: null,
        standardizeSelectionStart: false,
        static: true,
        align: 'center',
        sticky: false,
        updateOnEmptySelection: false
    },
    placeholder: {
        /* This example includes the default options for placeholder,
           if nothing is passed this is what it used */
        text: '輸入內容，選取文字範圍即可編輯',
        hideOnClick: true
    }
   
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
    	
     <div class="navbar-header">
            <h3><%= image_tag "brand_logo.png" %>願望清單 </h3>        
      </div>
      <nav class="nav ">
        <div class="container-fluid">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                </button>
          <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
          <li> <%= link_to '首頁', home_path%></li>
          <li> <%= link_to '關於我們', about_path %></li>
          <li><%= link_to 'Q&A', how_it_works_path %></li>
          <li><%= link_to '看大家的清單', latest_plans_path %></li>
          <li><%= link_to '前往個人頁面', plans_path %></li>
         
        </ul>
        <p class="login"> 哈囉! 
        <% if current_user %> 
          <%= current_user.nickname %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
          <%= link_to('更改資料', edit_registration_path(:user)) %>
        <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
          <%= link_to "Facebook登入", user_facebook_omniauth_authorize_path %>
        <% end %>
      </p>
        </div>
        </div>

      </nav>
    </div>



    <div class="body-info">
        
      <%= yield %>
    </div>

    <div class="footer text-center">
  
      <h6>©Copyright2017 VC </h6>

      <h6>使用本網站即視為同意本站隱私條款</h6>

    </div>

  </body>

</html>



<script>
 var editor = new MediumEditor('.editable', {
    toolbar: {
        allowMultiParagraphSelection: true,
        buttons: ['bold', 'italic', 'h4','orderedlist','unorderedlist'],
        diffLeft: 0,
        diffTop: -10,
        firstButtonClass: 'medium-editor-button-first',
        lastButtonClass: 'medium-editor-button-last',
        relativeContainer: null,
        standardizeSelectionStart: false,
        static: true,
        align: 'center',
        sticky: false,
        updateOnEmptySelection: false
    },
    placeholder: {
        /* This example includes the default options for placeholder,
           if nothing is passed this is what it used */
        text: '輸入內容，選取文字範圍即可編輯',
        hideOnClick: true
    }
   
});

</script>